# Kütüphaneler

In [1]:
import math
import random
import statistics
from collections import Counter
from typing import Dict, List, Tuple, Iterable
import numpy as np

# Soru 1 – Liste Metotları

In [2]:
notlar = [85, 92, 76, 92, 100, 76, 85, 92]
benzersiz = list(set(notlar))  # sıralı benzersiz
en_yuksek = max(notlar) 
en_dusuk = min(notlar) 
sirali = sorted(notlar)
print(f"Benzersiz Liste:{benzersiz}")
print(f"En yüksek not:{en_yuksek}")
print(f"En düşük not:{en_dusuk}")
print(f"Notların küçükten büyüğe sıralama:{sirali}")

Benzersiz Liste:[100, 92, 85, 76]
En yüksek not:100
En düşük not:76
Notların küçükten büyüğe sıralama:[76, 76, 85, 85, 92, 92, 92, 100]


# Soru 2 – Sayılar

In [3]:
def armstrong(sayi):
    toplam = 0
    for i in str(sayi):
        toplam += int(i) ** 3
    return toplam == sayi

for n in [153, 370, 371, 407, 123]:
    print(n, "->", armstrong(n))

153 -> True
370 -> True
371 -> True
407 -> True
123 -> False


# Soru 3 – Kümeler

In [4]:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}
print("Ortak:", A & B)
print("Sadece A:", A - B)
print("Birleşim:", sorted(A | B))

Ortak: {'Python', 'SQL'}
Sadece A: {'R', 'Java'}
Birleşim: ['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


# Soru 4 – Modüller

In [5]:
random.seed(123)
sayilar = [random.randint(1,100) for _ in range(10)]
print("Sayılar:", sayilar)
print("Ortalama:", statistics.mean(sayilar))
print("Std:", statistics.pstdev(sayilar))

Sayılar: [7, 35, 12, 99, 53, 35, 14, 5, 49, 69]
Ortalama: 37.8
Std: 28.89221348391293


# Soru 5 – Fonksiyonlar

In [6]:
def kelime_sayaci(metin):
    kelimeler = metin.lower().replace("!", "").replace(";", "").replace(".", "").split()
    toplam = len(kelimeler)
    en_uzun = max(kelimeler, key=len)
    en_sik = Counter(kelimeler).most_common(1)[0]
    return toplam, en_uzun, en_sik

metin = "Veri bilimi veri analizi ile birlikte veri! Bilimi; çok eğlenceli."
print(kelime_sayaci(metin))

(10, 'eğlenceli', ('veri', 3))


# Soru 6 – Gömülü Fonksiyonlar

In [7]:
sayilar = [5, 12, 7, 18, 24, 3, 16]
ciftler = list(filter(lambda x: x % 2 == 0, sayilar))
kareler = list(map(lambda x: x*x, ciftler))
print("Çiftler:", ciftler)
print("Kareler:", kareler)
print("Azalan:", sorted(kareler, reverse=True))

Çiftler: [12, 18, 24, 16]
Kareler: [144, 324, 576, 256]
Azalan: [576, 324, 256, 144]


# Soru 7 – Lambda İfadeleri

In [8]:
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]
print(sorted(kelimeler, key=lambda k: len(k)))

['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


# Soru 8 – Metodlar

In [9]:
def rakam_toplami(metin):
    toplam = 0
    sayi = ""
    for ch in metin:
        if ch.isdigit():
            sayi += ch
        else:
            if sayi:
                toplam += int(sayi)
                sayi = ""
    if sayi:
        toplam += int(sayi)
    return toplam

print(rakam_toplami("abc12def3"))
print(rakam_toplami("00x5y007"))

15
12


# Soru 9 – (Ekstra) Numpy 1

In [10]:
np.random.seed(123)
dizi = np.random.randint(0, 51, 10)
print("Dizi:", dizi)
print("Ortalama:", dizi.mean())
print("Standart sapma:", dizi.std())
print("En büyük değer:", dizi.max())

Dizi: [45  2 28 34 38 17 19 42 22 33]
Ortalama: 28.0
Standart sapma: 12.489995996796797
En büyük değer: 45


# Soru 10 – (Ekstra) Numpy 2

In [11]:
np.random.seed(123)
matris = np.random.rand(5, 5)
print("Matris:\n", matris)

sutun_ort = matris.mean(axis=0)
print("Sütun ortalamaları:", sutun_ort)

binary = (matris > 0.5).astype(int)
print("Binary matris:\n", binary)

Matris:
 [[0.69646919 0.28613933 0.22685145 0.55131477 0.71946897]
 [0.42310646 0.9807642  0.68482974 0.4809319  0.39211752]
 [0.34317802 0.72904971 0.43857224 0.0596779  0.39804426]
 [0.73799541 0.18249173 0.17545176 0.53155137 0.53182759]
 [0.63440096 0.84943179 0.72445532 0.61102351 0.72244338]]
Sütun ortalamaları: [0.56703001 0.60557535 0.4500321  0.44689989 0.55278034]
Binary matris:
 [[1 0 0 1 1]
 [0 1 1 0 0]
 [0 1 0 0 0]
 [1 0 0 1 1]
 [1 1 1 1 1]]


# Proje – “Kitap Satış Analiz Sistemi”

In [12]:
kitaplar = [
{"isim": "Veri Bilimi 101", "yazar": "Ali", "tur": "Bilim", "satis": 1200, "yil": 2021},
{"isim": "Python ile Yapay Zeka", "yazar": "Ayşe", "tur": "Bilim", "satis": 950, "yil": 2020},
{"isim": "İstatistik Temelleri", "yazar": "Ali", "tur": "Akademik", "satis": 700, "yil": 2019},
{"isim": "Makine Öğrenmesi", "yazar": "Can", "tur": "Bilim", "satis": 1800, "yil": 2022},
{"isim": "Veri Görselleştirme", "yazar": "Deniz", "tur": "Sanat", "satis": 400, "yil": 2018},
{"isim": "Matematiksel Modelleme", "yazar": "Ali", "tur": "Akademik", "satis": 1500, "yil": 2021},
{"isim": "Bilgi Toplumu", "yazar": "Ayşe", "tur": "Sosyal", "satis": 600, "yil": 2022}
]

In [13]:
en_cok = kitaplar[0]
for k in kitaplar:
    if k["satis"] > en_cok["satis"]:
        en_cok = k
print("En çok satan kitap:", en_cok["isim"])

yazarlar = {}
for k in kitaplar:
    y = k["yazar"]
    s = k["satis"]
    if y in yazarlar:
        yazarlar[y] = yazarlar[y] + s
    else:
        yazarlar[y] = s
print("Yazar satışları:", yazarlar)

turler = []
for k in kitaplar:
    if k["tur"] not in turler:
        turler.append(k["tur"])
print("Türler:", turler)

bin_ustu = []
for k in kitaplar:
    if k["satis"] > 1000:
        bin_ustu.append(k["isim"])
print("1000’den fazla satan kitaplar:", bin_ustu)

satislar = []
for k in kitaplar:
    satislar.append(k["satis"])
print("Ortalama satış:", statistics.mean(satislar))

print("Standart sapma:", statistics.pstdev(satislar))

En çok satan kitap: Makine Öğrenmesi
Yazar satışları: {'Ali': 3400, 'Ayşe': 1550, 'Can': 1800, 'Deniz': 400}
Türler: ['Bilim', 'Akademik', 'Sanat', 'Sosyal']
1000’den fazla satan kitaplar: ['Veri Bilimi 101', 'Makine Öğrenmesi', 'Matematiksel Modelleme']
Ortalama satış: 1021.4285714285714
Standart sapma: 468.9327874905672


In [14]:
import random
import statistics

# %70 train - %30 test
random.seed(123)
train = random.sample(kitaplar, int(len(kitaplar) * 0.7))
test = []
for k in kitaplar:
    if k not in train:
        test.append(k)

print("Train seti:", [k["isim"] for k in train])
print("Test seti:", [k["isim"] for k in test])

# Train seti analiz
train_satis = []
train_yazarlar = {}
for k in train:
    train_satis.append(k["satis"])
    y = k["yazar"]
    if y in train_yazarlar:
        train_yazarlar[y] = train_yazarlar[y] + 1
    else:
        train_yazarlar[y] = 1

print("\nTrain ortalama satış:", statistics.mean(train_satis))
print("Train yazar sıklıkları:", train_yazarlar)

# Test seti analiz
test_satis = []
test_yazarlar = {}
for k in test:
    test_satis.append(k["satis"])
    y = k["yazar"]
    if y in test_yazarlar:
        test_yazarlar[y] = test_yazarlar[y] + 1
    else:
        test_yazarlar[y] = 1

print("\nTest ortalama satış:", statistics.mean(test_satis))
print("Test yazar sıklıkları:", test_yazarlar)

# Karşılaştırma yorumu
if statistics.mean(train_satis) > statistics.mean(test_satis):
    print("\nYorum: Train setindeki ortalama satış test setinden daha yüksek.")
else:
    print("\nYorum: Test setindeki ortalama satış train setinden daha yüksek.")

Train seti: ['Veri Bilimi 101', 'İstatistik Temelleri', 'Bilgi Toplumu', 'Makine Öğrenmesi']
Test seti: ['Python ile Yapay Zeka', 'Veri Görselleştirme', 'Matematiksel Modelleme']

Train ortalama satış: 1075
Train yazar sıklıkları: {'Ali': 2, 'Ayşe': 1, 'Can': 1}

Test ortalama satış: 950
Test yazar sıklıkları: {'Ayşe': 1, 'Deniz': 1, 'Ali': 1}

Yorum: Train setindeki ortalama satış test setinden daha yüksek.
